import type { Metadata } from "next";
import { Inter as FontSans, Syne } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/login/header";
import { ThemeProvider } from "@/components/theme-provider";
import QueryProvider from "@/lib/context/query-provider";
import { Toaster } from "react-hot-toast";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSyne = Syne({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-syne",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSyne.variable, fontSans.variable)}>
        <Toaster />
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <QueryProvider>
            <Header />
            {children}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
